[workspace]
resolver = "2"
members = [
    "crates/api",
    "crates/askama",
    "crates/async-std",
    "crates/aws-lambda",
    "crates/aws-lambda-example",
    "crates/basic-auth",
    "crates/caching-headers",
    "crates/channels",
    "crates/client",
    "crates/compression",
    "crates/conn-id",
    "crates/cookies",
    "crates/example",
    "crates/forwarding",
    "crates/handlebars",
    "crates/head",
    "crates/http",
    "crates/logger",
    "crates/macros",
    "crates/method-override",
    "crates/native-tls",
    "crates/proxy",
    "crates/redirect",
    "crates/router",
    "crates/rustls",
    "crates/server-common",
    "crates/sessions",
    "crates/smol",
    "crates/sse",
    "crates/static",
    "crates/static-compiled",
    "crates/static-compiled-macros",
    "crates/tera",
    "crates/testing",
    "crates/tokio",
    "crates/trillium",
    "crates/websockets",
]
exclude = [
    "crates/controllers",
    "crates/fuzz",
]
