[package]
name = "trillium-opentelemetry-metrics"
version = "0.0.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2021"
description = "opentelemetry metrics for trillium.rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trillium-rs/trillium"
readme = "../README.md"
keywords = ["trillium", "framework", "async"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
opentelemetry = { version = "0.18.0", features = ["metrics"], default-features = false }
trillium = { path = "../trillium", version = "^0.2.0"}

[dev-dependencies]
opentelemetry-otlp = { version = "0.11.0", features = ["metrics", "tokio"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
trillium-router = { path = "../router" }
trillium-smol = { path = "../smol" }
trillium-testing = { path = "../testing" }
trillium-tokio = { path = "../tokio" }
tokio = "1.26.0"
